### ISSUE TITLE
关于nfs 与 ceph rbd的问题

### ISSUE THREAD

**Issue by fantastic2085** [tony-yin/ceph_scripts#1]
看到您的https://www.dazhuanlan.com/2019/10/15/5da59069bb158/

想请教一下 如果挂载的目录一直有写的操作 VIP切换的时候 能否umount掉呢？

**Comment by tony-yin** [comment]
VIP切换意味着原本提供服务的挂载目录，已经不可以访问了，所以也就不存在读写。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fuzhiyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 上午10:19
收件人:&nbsp;"tony-yin/ceph_scripts"<ceph_scripts@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[tony-yin/ceph_scripts] 关于nfs 与 ceph rbd的问题 (#1)





 
看到您的https://www.dazhuanlan.com/2019/10/15/5da59069bb158/
 
想请教一下 如果挂载的目录一直有写的操作 VIP切换的时候 能否umount掉呢？

**Comment by fantastic2085** [comment]
> VIP切换意味着原本提供服务的挂载目录，已经不可以访问了，所以也就不存在读写。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"fuzhiyu"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月6日(星期一) 上午10:19 收件人:&nbsp;"tony-yin/ceph_scripts"<ceph_scripts@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[tony-yin/ceph_scripts] 关于nfs 与 ceph rbd的问题 (#1) 看到您的https://www.dazhuanlan.com/2019/10/15/5da59069bb158/ 想请教一下 如果挂载的目录一直有写的操作 VIP切换的时候 能否umount掉呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fantastic2085** [comment]
举个场景:
按照https://www.dazhuanlan.com/2019/10/15/5da59069bb158/进行部署，然后暴露出去的目录，给k8s使用，通过k8s部署一个应用使用该目录，VIP切换时，应用是不会感知到的，那么应用内部还会继续有写操作的。应用比如是mysql等
